* Particles behave as waves, just like photons do
* These are called Matter Waves (https://en.wikipedia.org/wiki/Matter_wave)
* The heavier the particle, the shorter the wavelength
* Things like electrons and protons are much heavier than photons so they have much shorter wavelengths
* That's why the wave-like nature of matter particles wasn't noticed until De Broglie proposed their existence
* When a particle moves, its wavefunction spreads out until its position is observed
* When the particle's position is observed, its location is determined by the probabilities described by the wavefunction
* Because the wavefunction behaves like a wave, it interferes with itself to cause peaks and troughs
* The peaks and troughs determine the probability of finding the particle at a particular location
* If the wavefunction cancels itself out (adds up to 0) at any point, the particle will never been found there


In [41]:
import numpy as np

j = np.array([[0, 1, 2],
              [3, 2, 5],
              [6, 7, 8]])

print(j)



[[0 1 2]
 [3 2 5]
 [6 7 8]]


In [42]:
from IPython.display import display, Math

def print_matrix(name, matrix):
    row_sep = r"\\"
    col_sep = "&"
    display(Math(rf"""$$$
        \begin{{equation*}}
        {name} = 
        \begin{{pmatrix}}
        {row_sep.join(map(lambda row: col_sep.join(map(str, row)), matrix))}
        \end{{pmatrix}}
        \end{{equation*}}
    $$$"""))
    
print_matrix("a", j)

<IPython.core.display.Math object>